from typing import Protocol

from collections.abc import Sequence
from datetime import date, datetime

from app.domain.enums import OrderStatus, TradingMode
from app.domain.models.fill import Fill
from app.domain.models.market_bar import MarketBar
from app.domain.models.order import Order
from app.domain.models.portfolio import Portfolio
from app.domain.models.signal import MomentumSignal
from app.universe.models import ConstituentMembership


class MarketDataRepository(Protocol):
    def save_bars(self, bars: Sequence[MarketBar]) -> int: ...

    def get_bars(self, symbol: str, start: date, end: date) -> Sequence[MarketBar]: ...

    def get_latest_bar(self, symbol: str) -> MarketBar | None: ...


class SignalRepository(Protocol):
    def save_signals(self, signals: Sequence[MomentumSignal]) -> None: ...

    def get_signals(self, signal_date: date) -> Sequence[MomentumSignal]: ...

    def get_latest_signals(self) -> Sequence[MomentumSignal]: ...


class OrderRepository(Protocol):
    def save(self, order: Order, mode: TradingMode) -> Order: ...

    def get_by_id(self, order_id: int) -> Order: ...

    def get_by_client_order_id(self, client_order_id: str) -> Order: ...

    def get_open_orders(self) -> Sequence[Order]: ...

    def update_status(self, client_order_id: str, status: OrderStatus) -> Order: ...


class FillRepository(Protocol):
    def save(self, fill: Fill, order_db_id: int) -> Fill: ...

    def get_by_order_id(self, order_db_id: int) -> Sequence[Fill]: ...


class PortfolioRepository(Protocol):
    def save_snapshot(self, portfolio: Portfolio, timestamp: datetime) -> Portfolio: ...

    def get_latest_snapshot(self) -> Portfolio | None: ...


class SP500ConstituentRepository(Protocol):
    def get_memberships(self, symbol: str) -> Sequence[ConstituentMembership]: ...

    def get_memberships_as_of(self, as_of: date) -> Sequence[ConstituentMembership]: ...

    def get_all_memberships(self) -> Sequence[ConstituentMembership]: ...

    def upsert_memberships(self, memberships: Sequence[ConstituentMembership]) -> tuple[int, int]: ...
